### ISSUE TITLE
Old District Data [Tripura]

### ISSUE THREAD

**Issue by Baibhab97** [datameet/maps#47]
Describe the bug
The district data of Tripura is old.

Expected behaviour
8 districts are there in Tripura. Instead of 4, those 8 districts should be shown.
The name of the 8 districts are:
1. Dhalai
2. Gomati  
3. Khowai
4. North Tripura
5. Sipahijala  
6. South Tripura
7. Unokoti
8. West Tripura
(ref: https://tripura.gov.in/districtmap)

**Comment by devdattaT** [comment]
@Baibhab97 The districts in this Repo are as per the 2001 & 2011 census. They have not been updated as per the current districts, since such a national District Map does not exist.

You could look at https://github.com/justinelliotmeyers/India_Official_Boundaries_2019 if you want more up-to-date boundaries.
