### ISSUE TITLE
Wrong District names

### ISSUE THREAD

**Issue by ShantanuShinde** [datameet/maps#51]
Many of the names of district in the shapefile are wrong. For example, Ahmednagar is Ahmadnagar, Ahmedabad is Ahmadabad, and similar

**Comment by vijaybarve** [comment]
Where do we find standardized district names for all Indian states?

**Comment by vijaybarve** [comment]
https://github.com/datameet/maps/tree/master/Districts says Names and extent were derived from the Administrative Atlas of India, Census of India

**Comment by devdattaT** [comment]
The names of districts are as per the census. If you check https://censusindia.gov.in/2011census/dchb/DCHB.html, you will see the names match.

I know that the [Local Government Directory](https://lgdirectory.gov.in/) has different names, but I don't see any point in updating the names of the districts file, as it is as per the census 2011, and many districts have come up since then. 

You should know, that there has always been an issue with how [different govt departments count districts](https://qz.com/india/241183/how-many-districts-does-india-have-depends-on-who-you-ask/).
